import type { Metadata } from "next";
import { Inter, Azeret_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "../components/theme-provider";
import { ThemeToggle } from "../components/theme-toggle";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const azeretMono = Azeret_Mono({
  variable: "--font-azeret-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="w-full py-4 border-b border-slate-200 dark:border-slate-800">
      <div className="container mx-auto px-4 flex items-center justify-between">
        <Link href="/" className="font-medium text-xl">
          Whois<span className="text-claude-salmon">Jason</span>.me
        </Link>
        <div className="flex items-center space-x-4">
          <nav className="hidden md:flex space-x-6">
            <Link href="/" className="hover:text-claude-salmon transition-colors">
              Home
            </Link>
            <Link href="/Projects" className="hover:text-claude-salmon transition-colors">
              Projects
            </Link>
            <Link href="/#about" className="hover:text-claude-salmon transition-colors">
              About
            </Link>
            <Link href="/#Passions" className="hover:text-claude-salmon transition-colors">
              Passions
            </Link>
            <Link href="/contact" className="hover:text-claude-salmon transition-colors">
              Contact
            </Link>
          </nav>
          <div className="h-10 w-10">
            <ThemeToggle />
          </div>
          <div className="md:hidden">
            {/* Mobile menu button - not implementing full functionality here */}
            <button aria-label="Menu" className="p-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${azeretMono.variable} font-sans antialiased`}
      >
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
